#!/bin/bash

###########################################
# Cron Jobs Setup Script
# Zimbabwe Loyalty Platform
###########################################

set -e
set -u
set -o pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# Logging
log() {
    echo -e "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}

log_error() {
    echo -e "${RED}[$(date '+%Y-%m-%d %H:%M:%S')] ERROR:${NC} $1"
}

log_success() {
    echo -e "${GREEN}[$(date '+%Y-%m-%d %H:%M:%S')] SUCCESS:${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[$(date '+%Y-%m-%d %H:%M:%S')] WARNING:${NC} $1"
}

log "======================================"
log "  Cron Jobs Setup"
log "======================================"
log ""

# Create logs directory
mkdir -p "$PROJECT_DIR/logs"

# Create crontab content
CRONTAB_FILE="/tmp/loyalty-crontab-$$.txt"

cat > "$CRONTAB_FILE" <<EOF
# Zimbabwe Loyalty Platform - Scheduled Tasks
# Generated on $(date)
# DO NOT EDIT THIS FILE MANUALLY - use setup-cron.sh

# Environment
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
PROJECT_DIR=$PROJECT_DIR

# Daily database backup at 2:00 AM
0 2 * * * cd $PROJECT_DIR && bash $SCRIPT_DIR/backup.sh >> $PROJECT_DIR/logs/backup.log 2>&1

# Weekly database maintenance on Sunday at 3:00 AM
0 3 * * 0 cd $PROJECT_DIR && bash $SCRIPT_DIR/db-maintenance.sh >> $PROJECT_DIR/logs/maintenance.log 2>&1

# Database health check every 4 hours
0 */4 * * * cd $PROJECT_DIR && bash $SCRIPT_DIR/db-check.sh >> $PROJECT_DIR/logs/db-check.log 2>&1

# Clean up old logs every day at 4:00 AM (keep last 30 days)
0 4 * * * find $PROJECT_DIR/logs -name "*.log" -mtime +30 -delete

# Hourly reward expiry check (via API)
0 * * * * curl -X POST http://localhost:8080/internal/expire-rewards -H "X-Internal-Secret: \${INTERNAL_API_SECRET}" >> $PROJECT_DIR/logs/expiry.log 2>&1

# Monthly budget reset on 1st at midnight (via API)
0 0 1 * * curl -X POST http://localhost:8080/internal/reset-monthly-budgets -H "X-Internal-Secret: \${INTERNAL_API_SECRET}" >> $PROJECT_DIR/logs/budget-reset.log 2>&1

# Docker cleanup every week on Monday at 1:00 AM
0 1 * * 1 docker system prune -f --volumes >> $PROJECT_DIR/logs/docker-cleanup.log 2>&1

# Health check and notification every 15 minutes
*/15 * * * * cd $PROJECT_DIR && bash $SCRIPT_DIR/health-monitor.sh >> $PROJECT_DIR/logs/health-monitor.log 2>&1
EOF

log "Crontab file created: $CRONTAB_FILE"
log ""
log "Crontab contents:"
log "=================="
cat "$CRONTAB_FILE"
log "=================="
log ""

# Ask for confirmation
read -p "Install this crontab? (yes/no): " -r
echo

if [[ ! $REPLY =~ ^[Yy][Ee][Ss]$ ]]; then
    log "Installation cancelled"
    rm -f "$CRONTAB_FILE"
    exit 0
fi

# Install crontab
log "Installing crontab..."

if crontab "$CRONTAB_FILE"; then
    log_success "Crontab installed successfully"
else
    log_error "Failed to install crontab"
    rm -f "$CRONTAB_FILE"
    exit 1
fi

# Cleanup
rm -f "$CRONTAB_FILE"

# Show installed crontab
log ""
log "Installed crontab:"
crontab -l

log ""
log_success "Cron jobs setup completed"
log ""
log "Scheduled tasks:"
log "  - Daily backups at 2:00 AM"
log "  - Weekly DB maintenance on Sundays at 3:00 AM"
log "  - Hourly reward expiry checks"
log "  - Monthly budget reset on 1st at midnight"
log "  - Docker cleanup weekly on Mondays at 1:00 AM"
log "  - DB health check every 4 hours"
log "  - Health monitoring every 15 minutes"
log "  - Log cleanup daily at 4:00 AM"
log ""
log "To view logs:"
log "  tail -f $PROJECT_DIR/logs/backup.log"
log "  tail -f $PROJECT_DIR/logs/maintenance.log"
log "  tail -f $PROJECT_DIR/logs/db-check.log"
log ""
log "To remove cron jobs:"
log "  crontab -r"
log ""

exit 0
